# Thumzu's Tmux Config

# Sensible Settings
set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g mouse on

# Remap prefix key
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# Fix indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim-style switching panes
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Better splits
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Minimal Config

# Vague colorscheme statusbar
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'fg=color7 bg=default'
set -g status-right ''
set -g status-left '#S'
set -g status-left-style 'fg=color8'
set -g status-right-length 0
set -g status-left-length 100
setw -g window-status-current-style 'fg=colour6 bg=default bold'
setw -g window-status-current-format '#I:#W '
setw -g window-status-style 'fg=color8'
set -g message-style 'fg=color7 bg=default'       
set -g message-command-style 'fg=color7 bg=default'
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=cyan,dim

# Sessionizer
bind-key -r g run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Old catppuccin config

# # Configure the plugin

# set -g @catppuccin_flavor "macchiato"
# set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_status_background "none"

# set -g @catppuccin_window_current_text " #{b:pane_current_path}"
# set -g @catppuccin_window_text " #{b:pane_current_path}"

# Load catpuccin
# run ~/.config/tmux/plugins/catppuccin-tmux/catppuccin.tmux

# # Basics
# set-option -g status-position top
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_session}"

# # Customisation
# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""

# Reload Config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
